using MentolVKS.Model.Bases;
using System;
using System.Collections.Generic;

namespace MentolVKS.Model
{
    /// <summary>
    /// Модель конференций
    /// </summary>
    public class ConferenceCurrent : TableBasedEntityBase
    {
        /// <summary>
        /// Первичный ключ
        /// </summary>
        public int Idr { get; set; }
        /// <summary>
        /// GUID
        /// </summary>
        public Guid GUID { get; set; }
        /// <summary>
        /// OwnerID
        /// </summary>
        public int? OwnerID { get; set; }
        /// <summary>
        /// OwnerID
        /// </summary>
        public string OwnerJID { get; set; }
        
        /// <summary>
        /// CallID
        /// </summary>
        public string CallID { get; set; }
        /// <summary>
        /// URI
        /// </summary>
        public string URI { get; set; }
        /// <summary>
        /// StreamURL
        /// </summary>
        public string StreamURL { get; set; }
        /// <summary>
        /// StreamURL
        /// </summary>
        public string SecondaryURI { get; set; }
        /// <summary>
        /// Наименование конференции
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        ///  Description конференции
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// DefaultLayout
        /// </summary>
        public string DefaultLayout { get; set; }
        /// <summary>
        /// AutoGenerated 
        /// </summary>
        public bool? AutoGenerated { get; set; }
        /// <summary>
        /// NonMemberAccess 
        /// </summary>
        public bool? NonMemberAccess { get; set; }
        /// <summary>
        /// Secret 
        /// </summary>
        public string Secret { get; set; }
        /// <summary>
        /// CreateTime 
        /// </summary>
        public DateTime? CreateTime { get; set; }
        /// <summary>
        /// StartTime 
        /// </summary>
        public DateTime? StartTime { get; set; }
        /// <summary>
        /// EndTime 
        /// </summary>
        public DateTime? EndTime { get; set; }
        /// <summary>
        /// DateLastRecord 
        /// </summary>
        public DateTime? DateLastRecord { get; set; }

        /// <summary>
        /// Подчиненные коректные вызовы
        /// </summary>
        public ICollection<CallCurrent> CallCurrents { get; set; } = new HashSet<CallCurrent>();
    }
}
