DO $do$ BEGIN
if not exists(select 1 from pg_namespace where nspname = 'dbo') then 
begin
CREATE SCHEMA dbo;
end ;
END IF;END $do$;

DO $do$ BEGIN
if not exists(select 1 from pg_namespace where nspname = 'security') then 
begin
CREATE SCHEMA security;
end ;
END IF;END $do$;

ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT SELECT ON TABLES TO "lv";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT INSERT ON TABLES TO "lv";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT UPDATE ON TABLES TO "lv";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT DELETE ON TABLES TO "lv";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT EXECUTE ON FUNCTIONS TO "lv";
--для таблиц которые будут создаваться 
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT SELECT ON TABLES TO "lvrls";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT INSERT ON TABLES TO "lvrls";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT UPDATE ON TABLES TO "lvrls";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT DELETE ON TABLES TO "lvrls";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT EXECUTE ON FUNCTIONS TO "lvrls";

--CREATE SCHEMA dbo
--  AUTHORIZATION postgres;
--GRANT ALL ON SCHEMA dbo TO postgres;
GRANT ALL ON SCHEMA dbo TO lv; 
GRANT ALL ON SCHEMA dbo TO public;
GRANT dbo TO lv; 

GRANT USAGE ON SCHEMA security to lv;
GRANT USAGE ON SCHEMA security to lvrls;
GRANT USAGE ON SCHEMA security to public;

--разрешения для существующих таблиц
GRANT USAGE ON SCHEMA dbo TO lvrls;
GRANT ALL ON SCHEMA dbo TO lvrls; 
--GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbo TO lvrls;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dbo TO lvrls;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA dbo TO lvrls;
GRANT EXECUTE ON all FUNCTIONS IN SCHEMA dbo TO lvrls;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dbo TO lv;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA dbo TO lv;
GRANT EXECUTE ON all FUNCTIONS IN SCHEMA dbo TO lv;
GRANT EXECUTE ON all FUNCTIONS IN SCHEMA security TO lv;
GRANT EXECUTE ON all FUNCTIONS IN SCHEMA security TO lvrls;

ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT ALL ON TABLES TO lv;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT ALL ON FUNCTIONS TO lv;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT ALL ON TABLES TO lvrls;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT ALL ON FUNCTIONS TO lvrls;
ALTER DEFAULT PRIVILEGES IN SCHEMA security GRANT ALL ON FUNCTIONS TO lv;
ALTER DEFAULT PRIVILEGES IN SCHEMA security GRANT EXECUTE ON FUNCTIONS TO lv;
ALTER DEFAULT PRIVILEGES IN SCHEMA security GRANT EXECUTE ON FUNCTIONS TO lvrls;