using MentolVKS.Model.Bases;
using System;
using System.Collections.Generic;
using System.Text;

namespace MentolVKS.Model.BaseModel
{
	public class VksConferenceHistory : TableBasedEntityBase
	{
		public int Idr { get; set; } // int
		public Guid GUID { get; set; } // uniqueidentifier
		public int? OwnerID { get; set; } // int
		public string OwnerJID { get; set; } // varchar(100)
		public string CallID { get; set; } // varchar(50)
		public string URI { get; set; } // varchar(100)
		public string StreamURL { get; set; } // varchar(500)
		public string SecondaryURI { get; set; } // varchar(100)
		public string Name { get; set; } // varchar(100)
		public string Description { get; set; } // varchar(100)
		public string DefaultLayout { get; set; } // varchar(100)
		public bool AutoGenerated { get; set; } // bit
		public bool? NonMemberAccess { get; set; } // bit
		public string Secret { get; set; } // varchar(100)
		public DateTime? CreateTime { get; set; } // datetime
		public DateTime? StartTime { get; set; } // datetime
		public DateTime? EndTime { get; set; } // datetime
		public DateTime DateLastRecord { get; set; } // datetime
	}
}
